var jsonObj = {
   "imgdir":{
      "name":"01010000.img",
      "imgdir":[
         [
            [
               [
                  [
                     [
                        [
                           [
                              [
                                 [
                                    [
                                       [
                                          [
                                             [
                                                [
                                                   [
                                                      [
                                                         [
                                                            [
                                                               [
                                                                  [
                                                                     [
                                                                        [
                                                                           [
                                                                              {
                                                                                 "name":"info",
                                                                                 "int":[
                                                                                    [
                                                                                       [
                                                                                          [
                                                                                             [
                                                                                                [
                                                                                                   {
                                                                                                      "value":"0",
                                                                                                      "name":"reqJob"
                                                                                                   },
                                                                                                   {
                                                                                                      "name":"reqLevel",
                                                                                                      "value":"0"
                                                                                                   }
                                                                                                ],
                                                                                                {
                                                                                                   "name":"reqSTR",
                                                                                                   "value":"0"
                                                                                                }
                                                                                             ],
                                                                                             {
                                                                                                "name":"reqDEX",
                                                                                                "value":"0"
                                                                                             }
                                                                                          ],
                                                                                          {
                                                                                             "value":"0",
                                                                                             "name":"reqINT"
                                                                                          }
                                                                                       ],
                                                                                       {
                                                                                          "value":"0",
                                                                                          "name":"reqLUK"
                                                                                       }
                                                                                    ],
                                                                                    {
                                                                                       "name":"cash",
                                                                                       "value":"1"
                                                                                    }
                                                                                 ],
                                                                                 "string":[
                                                                                    {
                                                                                       "value":"Af",
                                                                                       "name":"islot"
                                                                                    },
                                                                                    {
                                                                                       "value":"Af",
                                                                                       "name":"vslot"
                                                                                    }
                                                                                 ],
                                                                                 "canvas":[
                                                                                    {
                                                                                       "name":"icon",
                                                                                       "vector":{
                                                                                          "x":"-4",
                                                                                          "name":"origin",
                                                                                          "y":"28"
                                                                                       },
                                                                                       "height":"28",
                                                                                       "width":"26"
                                                                                    },
                                                                                    {
                                                                                       "width":"24",
                                                                                       "height":"23",
                                                                                       "name":"iconRaw",
                                                                                       "vector":{
                                                                                          "x":"-4",
                                                                                          "name":"origin",
                                                                                          "y":"28"
                                                                                       }
                                                                                    }
                                                                                 ]
                                                                              },
                                                                              {
                                                                                 "canvas":{
                                                                                    "vector":{
                                                                                       "y":"25",
                                                                                       "name":"origin",
                                                                                       "x":"15"
                                                                                    },
                                                                                    "string":{
                                                                                       "value":"accessoryFace",
                                                                                       "name":"z"
                                                                                    },
                                                                                    "imgdir":{
                                                                                       "name":"map",
                                                                                       "vector":{
                                                                                          "x":"-10",
                                                                                          "y":"-44",
                                                                                          "name":"brow"
                                                                                       }
                                                                                    },
                                                                                    "name":"default",
                                                                                    "width":"9",
                                                                                    "height":"10"
                                                                                 },
                                                                                 "name":"default"
                                                                              }
                                                                           ],
                                                                           {
                                                                              "imgdir":[
                                                                                 [
                                                                                    {
                                                                                       "uol":{
                                                                                          "value":"../../default/default",
                                                                                          "name":"default"
                                                                                       },
                                                                                       "name":"0"
                                                                                    },
                                                                                    {
                                                                                       "uol":{
                                                                                          "name":"default",
                                                                                          "value":"../../default/default"
                                                                                       },
                                                                                       "name":"1"
                                                                                    }
                                                                                 ],
                                                                                 {
                                                                                    "uol":{
                                                                                       "name":"default",
                                                                                       "value":"../../default/default"
                                                                                    },
                                                                                    "name":"2"
                                                                                 }
                                                                              ],
                                                                              "name":"blink"
                                                                           }
                                                                        ],
                                                                        {
                                                                           "name":"hit",
                                                                           "imgdir":{
                                                                              "uol":{
                                                                                 "name":"default",
                                                                                 "value":"../../default/default"
                                                                              },
                                                                              "name":"0"
                                                                           }
                                                                        }
                                                                     ],
                                                                     {
                                                                        "imgdir":{
                                                                           "name":"0",
                                                                           "canvas":{
                                                                              "height":"10",
                                                                              "name":"default",
                                                                              "vector":{
                                                                                 "y":"25",
                                                                                 "name":"origin",
                                                                                 "x":"15"
                                                                              },
                                                                              "string":{
                                                                                 "value":"accessoryFace",
                                                                                 "name":"z"
                                                                              },
                                                                              "width":"11",
                                                                              "imgdir":{
                                                                                 "vector":{
                                                                                    "x":"-10",
                                                                                    "y":"-45",
                                                                                    "name":"brow"
                                                                                 },
                                                                                 "name":"map"
                                                                              }
                                                                           }
                                                                        },
                                                                        "name":"smile"
                                                                     }
                                                                  ],
                                                                  {
                                                                     "name":"troubled",
                                                                     "imgdir":{
                                                                        "canvas":{
                                                                           "height":"10",
                                                                           "width":"9",
                                                                           "vector":{
                                                                              "x":"15",
                                                                              "name":"origin",
                                                                              "y":"25"
                                                                           },
                                                                           "string":{
                                                                              "name":"z",
                                                                              "value":"accessoryFace"
                                                                           },
                                                                           "imgdir":{
                                                                              "name":"map",
                                                                              "vector":{
                                                                                 "y":"-44",
                                                                                 "x":"-8",
                                                                                 "name":"brow"
                                                                              }
                                                                           },
                                                                           "name":"default"
                                                                        },
                                                                        "name":"0"
                                                                     }
                                                                  }
                                                               ],
                                                               {
                                                                  "imgdir":{
                                                                     "canvas":{
                                                                        "width":"9",
                                                                        "vector":{
                                                                           "y":"25",
                                                                           "name":"origin",
                                                                           "x":"15"
                                                                        },
                                                                        "string":{
                                                                           "value":"accessoryFace",
                                                                           "name":"z"
                                                                        },
                                                                        "imgdir":{
                                                                           "vector":{
                                                                              "x":"-9",
                                                                              "y":"-42",
                                                                              "name":"brow"
                                                                           },
                                                                           "name":"map"
                                                                        },
                                                                        "height":"10",
                                                                        "name":"default"
                                                                     },
                                                                     "name":"0"
                                                                  },
                                                                  "name":"cry"
                                                               }
                                                            ],
                                                            {
                                                               "name":"angry",
                                                               "imgdir":{
                                                                  "name":"0",
                                                                  "canvas":{
                                                                     "vector":{
                                                                        "y":"25",
                                                                        "x":"15",
                                                                        "name":"origin"
                                                                     },
                                                                     "string":{
                                                                        "name":"z",
                                                                        "value":"accessoryFace"
                                                                     },
                                                                     "height":"15",
                                                                     "imgdir":{
                                                                        "vector":{
                                                                           "y":"-43",
                                                                           "x":"-10",
                                                                           "name":"brow"
                                                                        },
                                                                        "name":"map"
                                                                     },
                                                                     "name":"default",
                                                                     "width":"11"
                                                                  }
                                                               }
                                                            }
                                                         ],
                                                         {
                                                            "imgdir":{
                                                               "canvas":{
                                                                  "width":"9",
                                                                  "vector":{
                                                                     "x":"15",
                                                                     "name":"origin",
                                                                     "y":"25"
                                                                  },
                                                                  "string":{
                                                                     "value":"accessoryFace",
                                                                     "name":"z"
                                                                  },
                                                                  "imgdir":{
                                                                     "name":"map",
                                                                     "vector":{
                                                                        "y":"-44",
                                                                        "x":"-10",
                                                                        "name":"brow"
                                                                     }
                                                                  },
                                                                  "name":"default",
                                                                  "height":"10"
                                                               },
                                                               "name":"0"
                                                            },
                                                            "name":"bewildered"
                                                         }
                                                      ],
                                                      {
                                                         "name":"stunned",
                                                         "imgdir":{
                                                            "name":"0",
                                                            "uol":{
                                                               "value":"../../bewildered/0/default",
                                                               "name":"default"
                                                            }
                                                         }
                                                      }
                                                   ],
                                                   {
                                                      "imgdir":[
                                                         {
                                                            "name":"0",
                                                            "canvas":{
                                                               "name":"default",
                                                               "width":"2",
                                                               "height":"6",
                                                               "vector":{
                                                                  "x":"15",
                                                                  "name":"origin",
                                                                  "y":"25"
                                                               },
                                                               "string":{
                                                                  "value":"accessoryFace",
                                                                  "name":"z"
                                                               },
                                                               "imgdir":{
                                                                  "vector":{
                                                                     "name":"brow",
                                                                     "x":"-18",
                                                                     "y":"-44"
                                                                  },
                                                                  "name":"map"
                                                               }
                                                            }
                                                         },
                                                         {
                                                            "uol":{
                                                               "name":"default",
                                                               "value":"../0/default"
                                                            },
                                                            "name":"1"
                                                         }
                                                      ],
                                                      "name":"vomit"
                                                   }
                                                ],
                                                {
                                                   "imgdir":{
                                                      "name":"0",
                                                      "canvas":{
                                                         "name":"default",
                                                         "vector":{
                                                            "name":"origin",
                                                            "y":"25",
                                                            "x":"15"
                                                         },
                                                         "string":{
                                                            "value":"accessoryFace",
                                                            "name":"z"
                                                         },
                                                         "imgdir":{
                                                            "name":"map",
                                                            "vector":{
                                                               "name":"brow",
                                                               "x":"-8",
                                                               "y":"-44"
                                                            }
                                                         },
                                                         "height":"10",
                                                         "width":"9"
                                                      }
                                                   },
                                                   "name":"oops"
                                                }
                                             ],
                                             {
                                                "imgdir":{
                                                   "name":"0",
                                                   "canvas":{
                                                      "height":"10",
                                                      "name":"default",
                                                      "width":"9",
                                                      "vector":{
                                                         "y":"25",
                                                         "name":"origin",
                                                         "x":"15"
                                                      },
                                                      "string":{
                                                         "name":"z",
                                                         "value":"accessoryFaceBelowFace"
                                                      },
                                                      "imgdir":{
                                                         "vector":{
                                                            "y":"-44",
                                                            "x":"-10",
                                                            "name":"brow"
                                                         },
                                                         "name":"map"
                                                      }
                                                   }
                                                },
                                                "name":"cheers"
                                             }
                                          ],
                                          {
                                             "name":"chu",
                                             "imgdir":{
                                                "canvas":{
                                                   "height":"10",
                                                   "name":"default",
                                                   "width":"9",
                                                   "vector":{
                                                      "y":"25",
                                                      "x":"15",
                                                      "name":"origin"
                                                   },
                                                   "string":{
                                                      "name":"z",
                                                      "value":"accessoryFace"
                                                   },
                                                   "imgdir":{
                                                      "vector":{
                                                         "y":"-44",
                                                         "name":"brow",
                                                         "x":"-8"
                                                      },
                                                      "name":"map"
                                                   }
                                                },
                                                "name":"0"
                                             }
                                          }
                                       ],
                                       {
                                          "name":"wink",
                                          "imgdir":{
                                             "name":"0",
                                             "canvas":{
                                                "name":"default",
                                                "width":"9",
                                                "vector":{
                                                   "y":"25",
                                                   "x":"15",
                                                   "name":"origin"
                                                },
                                                "string":{
                                                   "value":"accessoryFace",
                                                   "name":"z"
                                                },
                                                "height":"10",
                                                "imgdir":{
                                                   "vector":{
                                                      "y":"-44",
                                                      "x":"-9",
                                                      "name":"brow"
                                                   },
                                                   "name":"map"
                                                }
                                             }
                                          }
                                       }
                                    ],
                                    {
                                       "imgdir":{
                                          "canvas":{
                                             "vector":{
                                                "y":"25",
                                                "x":"15",
                                                "name":"origin"
                                             },
                                             "string":{
                                                "name":"z",
                                                "value":"accessoryFace"
                                             },
                                             "width":"9",
                                             "imgdir":{
                                                "vector":{
                                                   "y":"-44",
                                                   "x":"-8",
                                                   "name":"brow"
                                                },
                                                "name":"map"
                                             },
                                             "height":"10",
                                             "name":"default"
                                          },
                                          "name":"0"
                                       },
                                       "name":"pain"
                                    }
                                 ],
                                 {
                                    "name":"glitter",
                                    "imgdir":[
                                       {
                                          "name":"0",
                                          "uol":{
                                             "name":"default",
                                             "value":"../../default/default"
                                          }
                                       },
                                       {
                                          "name":"1",
                                          "uol":{
                                             "name":"default",
                                             "value":"../../default/default"
                                          }
                                       }
                                    ]
                                 }
                              ],
                              {
                                 "imgdir":{
                                    "name":"0",
                                    "canvas":{
                                       "vector":{
                                          "y":"25",
                                          "x":"15",
                                          "name":"origin"
                                       },
                                       "width":"9",
                                       "string":{
                                          "value":"accessoryFaceBelowFace",
                                          "name":"z"
                                       },
                                       "height":"10",
                                       "imgdir":{
                                          "name":"map",
                                          "vector":{
                                             "y":"-43",
                                             "name":"brow",
                                             "x":"-10"
                                          }
                                       },
                                       "name":"default"
                                    }
                                 },
                                 "name":"shine"
                              }
                           ],
                           {
                              "name":"blaze",
                              "imgdir":[
                                 {
                                    "name":"0",
                                    "canvas":{
                                       "name":"default",
                                       "vector":{
                                          "name":"origin",
                                          "y":"25",
                                          "x":"15"
                                       },
                                       "string":{
                                          "value":"accessoryFaceBelowFace",
                                          "name":"z"
                                       },
                                       "imgdir":{
                                          "name":"map",
                                          "vector":{
                                             "name":"brow",
                                             "x":"-13",
                                             "y":"-47"
                                          }
                                       },
                                       "height":"8",
                                       "width":"10"
                                    }
                                 },
                                 {
                                    "name":"1",
                                    "uol":{
                                       "name":"default",
                                       "value":"../0/default"
                                    }
                                 }
                              ]
                           }
                        ],
                        {
                           "name":"love",
                           "imgdir":[
                              {
                                 "name":"0",
                                 "canvas":{
                                    "height":"10",
                                    "vector":{
                                       "x":"15",
                                       "y":"25",
                                       "name":"origin"
                                    },
                                    "string":{
                                       "value":"accessoryFaceBelowFace",
                                       "name":"z"
                                    },
                                    "name":"default",
                                    "imgdir":{
                                       "vector":{
                                          "y":"-46",
                                          "x":"-10",
                                          "name":"brow"
                                       },
                                       "name":"map"
                                    },
                                    "width":"10"
                                 }
                              },
                              {
                                 "name":"1",
                                 "uol":{
                                    "name":"default",
                                    "value":"../0/default"
                                 }
                              }
                           ]
                        }
                     ],
                     {
                        "name":"despair",
                        "imgdir":[
                           {
                              "name":"0",
                              "canvas":{
                                 "name":"default",
                                 "vector":{
                                    "y":"25",
                                    "name":"origin",
                                    "x":"15"
                                 },
                                 "string":{
                                    "value":"accessoryFaceBelowFace",
                                    "name":"z"
                                 },
                                 "height":"11",
                                 "imgdir":{
                                    "vector":{
                                       "y":"-45",
                                       "x":"-12",
                                       "name":"brow"
                                    },
                                    "name":"map"
                                 },
                                 "width":"9"
                              }
                           },
                           {
                              "uol":{
                                 "name":"default",
                                 "value":"../0/default"
                              },
                              "name":"1"
                           }
                        ]
                     }
                  ],
                  {
                     "name":"hum",
                     "imgdir":[
                        {
                           "canvas":{
                              "height":"10",
                              "vector":{
                                 "x":"16",
                                 "name":"origin",
                                 "y":"27"
                              },
                              "string":{
                                 "value":"accessoryFaceBelowFace",
                                 "name":"z"
                              },
                              "imgdir":{
                                 "vector":{
                                    "x":"-11",
                                    "name":"brow",
                                    "y":"-48"
                                 },
                                 "name":"map"
                              },
                              "width":"10",
                              "name":"default"
                           },
                           "name":"0"
                        },
                        {
                           "uol":{
                              "name":"default",
                              "value":"../0/default"
                           },
                           "name":"1"
                        }
                     ]
                  }
               ],
               {
                  "name":"bowing",
                  "imgdir":[
                     {
                        "canvas":{
                           "height":"10",
                           "vector":{
                              "x":"15",
                              "name":"origin",
                              "y":"25"
                           },
                           "string":{
                              "value":"accessoryFaceBelowFace",
                              "name":"z"
                           },
                           "imgdir":{
                              "name":"map",
                              "vector":{
                                 "x":"-10",
                                 "name":"brow",
                                 "y":"-46"
                              }
                           },
                           "width":"10",
                           "name":"default"
                        },
                        "name":"0"
                     },
                     {
                        "uol":{
                           "value":"../0/default",
                           "name":"default"
                        },
                        "name":"1"
                     }
                  ]
               }
            ],
            {
               "imgdir":[
                  {
                     "canvas":{
                        "height":"10",
                        "width":"10",
                        "vector":{
                           "name":"origin",
                           "x":"15",
                           "y":"25"
                        },
                        "string":{
                           "value":"accessoryFaceBelowFace",
                           "name":"z"
                        },
                        "name":"default",
                        "imgdir":{
                           "vector":{
                              "name":"brow",
                              "y":"-46",
                              "x":"-10"
                           },
                           "name":"map"
                        }
                     },
                     "name":"0"
                  },
                  {
                     "name":"1",
                     "uol":{
                        "value":"../0/default",
                        "name":"default"
                     }
                  }
               ],
               "name":"hot"
            }
         ],
         {
            "name":"dam",
            "imgdir":[
               {
                  "canvas":{
                     "height":"10",
                     "vector":{
                        "name":"origin",
                        "x":"15",
                        "y":"25"
                     },
                     "string":{
                        "value":"accessoryFaceBelowFace",
                        "name":"z"
                     },
                     "name":"default",
                     "imgdir":{
                        "vector":{
                           "name":"brow",
                           "x":"-10",
                           "y":"-46"
                        },
                        "name":"map"
                     },
                     "width":"10"
                  },
                  "name":"0"
               },
               {
                  "uol":{
                     "value":"../0/default",
                     "name":"default"
                  },
                  "name":"1"
               }
            ]
         }
      ]
   }
};